function handles=wc_create_detailsfigure(handles)

%figure
handles.hdetailsfig=figure('Visible','Off','Units','Normalized','Position',[0 0 1 0.9],...
    'Paperunits','Normalized','Paperorientation','Landscape','PaperPosition',[0.01 0.01 0.98 0.98],...
    'UserData',handles.mainfig,...
    'CloseRequestFcn',{@closedetails_callback},...
    'Name','Details','NumberTitle','off','Tag','Details');

nrow=3;ncol=5;
stepx=0.04; width=(1-(ncol+1)*stepx)/ncol;
stepy=0.03; hight=(1-(nrow+1)*stepy)/nrow;
%axes to show how spike shapes do change in time (5 intervals)
%last row
for i=1:ncol,
    handles.hdetailsspikeaxes(i)=axes(...
        'position',[stepx+(width+stepx)*mod(i-1,ncol) 1-(stepy+hight)*( 3 ) width hight],...
        'Tag',sprintf('DetailsSpikes%d',i));
end

%axes to show average spike shapes for 5 time intervals
i=1;
handles.hdetailsaveragespikesaxes=axes(...
    'position',[stepx+(width+stepx)*mod(i-1,ncol) 1-(stepy+hight)*( 1 ) width hight],...
    'Tag',sprintf('DetailsAverageSpikes'));
handles.hdetailsisiaxes=axes(...
    'position',[stepx+(width+stepx)*mod(i-1,ncol) 1-(stepy+hight)*( 2 )+0.1*hight width hight*0.9],...
    'Tag',sprintf('DetailsISI'));

%axes to plot all spikes of this cluster
%(maybe most distant only since the plot is dedicated to removal of bad spikes)
i=2;
handles.hdetailsallspikes=axes(...
    'position',[stepx+(width+stepx)*mod(i-1,ncol) 1-(stepy+hight)*( 1 )+0.07*hight width 0.93*hight],...
    'Tag',sprintf('DetailsAllSpikes'),'xtick',[]);

handles.hdetailstoplot = uicontrol('units','normalized','Style','popupmenu','FontSize',12,...
    'String',{'All','5%','10%','20%','50%'},...
    'Tag','detailstoplot',...
    'Value',2,...
    'UserData',handles.mainfig,...
    'Callback',{@changehdetailstoplot},...
    'Position',[(width+stepx)*mod(i-1,ncol) 1-stepy 0.05 0.03]);

%slider to changing amount of spikes  
v=100;%random number, will be properly initialized 
handles.hdetailsallspikessliderH=uicontrol('units','normalized','Style','slider','FontSize',12,...
    'Tag','allspikessliderH',...
    'UserData',handles.mainfig,...
    'Position',[stepx+(width+stepx)*1 1-(stepy+hight) width 0.07*hight],...
    'Callback',{@getallspikessliderH});
% handles.hdetailsallspikessliderH_prev=v;
%     'Min',0,'Max',v,'SliderStep',[0.1 0.2],'Value',v,...

%slider changing the step to use in changing amount of spikes
v=100;
handles.hdetailsallspikessliderV=uicontrol('units','normalized','Style','slider','FontSize',12,...
    'Tag','allspikessliderV',...
    'UserData',handles.mainfig,...
    'Position',[...
        stepx+(width+stepx)*1+width...
        1-(stepy+hight)*( 1 )+(0.07-0.07)*hight...
        0.07*width hight*(1)],...
    'Callback',{@getallspikessliderV});
%     'Min',1,'Max',v,'SliderStep',[0.001 0.01],'Value',v,...

handles.hdetailstextStep=uicontrol('units','normalized','Style','Text','String','100','FontSize',12,...
    'horizontalalignment','center',...
    'Tag','textStep',...
    'UserData',handles.mainfig,...
    'Position',[stepx+(width+stepx)+width...
        1-stepy...
        0.12*width 0.12*width]);


%axes to show closeby spikes
i=2;
handles.hdetailsclosebyspikes=axes(...
    'position',[stepx+(width+stepx)*mod(i-1,ncol) 1-(stepy+hight)*( 2 )+0.1*hight width hight*0.9],...
    'Tag',sprintf('DetailsClosebySpikes'),'xtick',[]);
handles.hdetailsclosebyspikesslider=uicontrol('units','normalized','Style','slider','FontSize',12,...
    'Min',0,'Max',length(handles.MINISI),'SliderStep',[1/length(handles.MINISI) 0.1],'Value',28,...
    'Tag','closebyspikeslider',...
    'UserData',handles.mainfig,...
    'Position',[stepx+(width+stepx)*1 1-(stepy+hight)*( 2 )+stepy-0.07*hight width 0.07*hight],...
    'Callback',{@getminisislider});
handles.hdetailsprune=uicontrol('units','normalized','Style','togglebutton','String','Prune','FontSize',12,...
    'Tag','detailsprune',...
    'UserData',handles.mainfig,...
    'position',[stepx+(width+stepx)*1+width/2 1-(stepy+hight)-stepy 0.03 0.025],...
    'Callback',{@details_prunebutton});
% handles.hdetailsprune1=uicontrol('units','normalized','Style','pushbutton','String','Prune1','FontSize',12,...
%     'Tag','detailsprune1',...
%     'UserData',handles.mainfig,...
%     'position',[stepx+(width+stepx)*1+width/2+0.04 1-(stepy+hight)-stepy 0.035 0.025],...
%     'Callback',{@details_prune1button});

i=3;
handles.hdetailshistogram=axes(...
    'position',[stepx+(width+stepx)*mod(i-1,ncol) 1-(stepy+hight)*( 1 ) (width+stepx)*3-stepx hight],...
    'Tag',sprintf('DetailsHist'));

for i=3:ncol,
    j=i-2;
    handles.hdetailsfeatures(j)=axes(...
        'position',[stepx+(width+stepx)*mod(i-1,ncol) 1-(stepy+hight)*( 2 )+0.1*hight width hight*0.9],...
        'Tag',sprintf('DetailsFeatures%d',i));
end

handles.hdetailsprint=uicontrol('units','normalized','Style','pushbutton','String','Print','FontSize',12,...
    'Tag','detailssave',...
    'UserData',handles.mainfig,...
    'Position',[stepx+(width+stepx)*4 1-stepy*0.99 0.05 0.03],...
    'Callback',{@detailsprintbutton});

handles.hdetailsaccept=uicontrol('units','normalized','Style','pushbutton','String','Accept','FontSize',12,...
    'Tag','detailsaccept',...
    'UserData',handles.mainfig,...
    'Position',[stepx+(width+stepx)*4+0.05 1-stepy*0.99 0.05 0.03],...
    'Callback',{@detailsacceptbutton});

handles.hdetailsreplot=uicontrol('units','normalized','Style','pushbutton','String','Replot','FontSize',12,...
    'Tag','detailsreplot',...
    'UserData',handles.mainfig,...
    'Position',[stepx+(width+stepx)*4+0.10 1-stepy*0.99 0.05 0.03],...
    'Callback',{@detailsreplotbutton});

function changehdetailstoplot(source,eventdata)
handles=guidata(get(source,'UserData'));
handles=details_removedistantspikes(handles);
% Update handles structure
guidata(handles.mainfig, handles);

function detailsprintbutton(source,eventdata)
handles=guidata(get(source,'UserData'));
name=sprintf('ch%dcl%d-%s-detailsfig.jpg',handles.channel,handles.details_currcluster,handles.bname);
h=waitbar(1,sprintf('Saving figure into file %s',name));
print(handles.hdetailsfig,'-djpeg',name);
close(h)

function detailsreplotbutton(source,eventdata)
handles=guidata(get(source,'UserData'));
plot_details_shapeevolution(handles);
plot_details_instFR(handles);
plot_details_distinctfeatures(handles);


function detailsacceptbutton(source,eventdata)
handles=guidata(get(source,'UserData'));
handles=wc_details_accept(handles);
handles=plot_spikes_isi(handles);
if ~all(handles.ts==0), plot_ts(handles); end
set(handles.hdetailsfig,'Visible','Off');
set(handles.mainfig,'Visible','On');

% Update handles structure
guidata(handles.mainfig, handles);

function getminisislider(source,eventdata)
handles=guidata(get(source,'UserData'));
minisi=get(source,'Value');
minisi=round(minisi);
set(source,'Value',minisi);
plot_details_closebyspikes(handles);

function getallspikessliderH(source,eventdata)
handles=guidata(get(source,'UserData'));
handles=details_removedistantspikes(handles);

plot_details_closebyspikes(handles);

% Update handles structure
guidata(handles.mainfig, handles);

function getallspikessliderV(source,eventdata)
%change step and show it
handles=guidata(get(source,'UserData'));
axes(handles.hdetailsallspikes);
step=round(get(handles.hdetailsallspikessliderV,'Value'));
set(handles.hdetailstextStep,'String',num2str(step));
handles=details_removedistantspikes(handles);
% Update handles structure
guidata(handles.mainfig, handles);

%? set([handles.detailsspikeaxes handles.detailsisiaxes],'color','white');

%save button?
%toplot button
%histogram of spike counts over time
%hitograms of n best separating features 

function closedetails_callback(source,eventdata)
%does not really close, makes it invisible
handles=guidata(get(source,'UserData'));
set(handles.hdetailsfig,'Visible','Off');
set(handles.mainfig,'Visible','On');

function details_prunebutton(source, eventdata)
handles=guidata(get(source,'UserData'));
handles=wc_details_prune(handles);


function details_prune1button(source, eventdata)
fprintf('Not yet implemented\n');